{% set name = "u-msgpack-python" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b801a83d6ed75e6df41e44518b4f2a9c221dc2da4bcd5380e3a0feda520bc61a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - umsgpack

about:
  home: https://github.com/vsergeev/u-msgpack-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A portable, lightweight MessagePack serializer and deserializer written in pure Python.
  dev_url: https://github.com/vsergeev/u-msgpack-python

extra:
  recipe-maintainers:
    - tschoonj
